### ISSUE TITLE
Questionable files checked in

### ISSUE THREAD

**Issue by vanderhe** [Teoroo-CMC/CCS#9]
There are some files/directories where it is unclear to me (or at least questionable) if they should be checked in to the repository. Examples include:

- [.vscode](https://github.com/Teoroo-CMC/CCS/tree/52d9b5abb2e83b1dae92cb03972be3e5db077c6c/.vscode)/settings.json
- [docs](https://github.com/Teoroo-CMC/CCS/tree/52d9b5abb2e83b1dae92cb03972be3e5db077c6c/docs)/_build/
- [examples](https://github.com/Teoroo-CMC/CCS/tree/52d9b5abb2e83b1dae92cb03972be3e5db077c6c/examples)/.ipynb_checkpoints/
- [examples](https://github.com/Teoroo-CMC/CCS/tree/52d9b5abb2e83b1dae92cb03972be3e5db077c6c/examples)/Untitled.ipynb

A more sophisticated [.gitignore](https://github.com/Teoroo-CMC/CCS/blob/52d9b5abb2e83b1dae92cb03972be3e5db077c6c/.gitignore) would be nice to have.

E.g. we could move towards one of these templates:
https://github.com/github/gitignore

**Comment by ThijsSmolders** [comment]
Hi Tamoo, many thanks for your input! I've cleaned up the source code and taken up your excellent suggestion of expanding on the .gitignore side! Have a nice weekend!
